version: "3.9"

networks:
    algafood-network:
        driver: bridge

services:
    algafood-mysql:
        image: mysql:8.0
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
            - "3306:3306"
        networks:
            - algafood-network

    algafood-redis:
        image: redis:6.2.1-alpine
        ports:
            - "6379:6379"
        networks:
            - algafood-network

    algafood-api:
        image: algafood-api:0.0.1-SNAPSHOT
        command:
            [
                "/wait-for-it.sh",
                "algafood-mysql:3306",
                "-t",
                "30",
                "--",
                "java",
                "-jar",
                "algafoodapi.jar",
            ]
        environment:
            DB_HOST: algafood-mysql
            SPRING_SESSION_STORE_TYPE: redis
            SPRING_REDIS_HOST: algafood-redis
        #ports:
        # - "8080:8080"
        networks:
            - algafood-network
        depends_on:
            - algafood-mysql
        #deploy:
        # replicas: 2
    algafood-proxy:
        build: ./nginx
        image: algafood-proxy
        ports:
            - "80:80"
        networks:
            - algafood-network
        depends_on:
            - algafood-api
